<?php

namespace Core;

define(ROOT, dirname($_SERVER['SCRIPT_FILENAME']));
define(CORE_PATH, ROOT . "/" . "core");
define(APP_PATH, ROOT . "/application");

// autoload.php @generated by Composer
include ROOT . '/vendor/autoload.php';
include Lu . '/common/functions.php';
//dump(get_defined_constants());

defined(DEBUG) or define(DEBUG, false);

if (DEBUG) {
    $whoops = new \Whoops\Run();
    $whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler());
    $whoops->register();
    ini_set('display_errors', 'On');
//    error_reporting(E_ALL ^ E_NOTICE);
} else {
    ini_set('display_errors', 'Off');
}

require CORE_PATH . '/library/Lu.class.php';
spl_autoload_register('\core\library\Lu::load');
\core\library\Lu::run();